on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
jobs:
  singularity:
    runs-on:
      - self-hosted
      - "can-fetch"
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: execute
        run: ./ping.sh
        shell: bash
env:
  RHSTATUS_PROXY_SECRET: ${{secrets.RHSTATUS_PROXY_SECRET}}
